#name of workflow

name: Application CI/CD

on:
  push:
    branches: [main,master]
    paths:
      - 'terraform/**'
      - '.github/workflows/cicd.yml'
      - 'Dockerfile'
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform Action'
        required: true
        default: 'Destroy'
        type: choice
        options:
          - 'Destroy'

jobs:
  security-scan:
    runs-on: ubuntu-latest
    if: github.event.inputs.action != 'Destroy'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Checkov
        run: |
          pip install checkov

      - name: Run Checkov
        run: checkov -d terraform --framework terraform -s 

  docker-build:
    runs-on: ubuntu-latest
    if: github.event.inputs.action != 'Destroy'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ballsimulatorapp:latest .
      
      - name: Run trivy for scanning
        uses: aquasecurity/trivy-action@v0.28.0
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/ballsimulatorapp:latest
          format: table
          exit-code: 1
          severity: HIGH,CRITICAL
    
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ballsimulatorapp:latest

  terraform-apply:
    needs: [docker-build, security-scan]
    runs-on: ubuntu-latest
    if: github.event.inputs.action != 'Destroy'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_CLOUD_TOKEN }}
          terraform_version: 1.5.7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: |
          cd terraform
          terraform init
    
      - name: Terraform Validate
        run: |
          cd terraform
          terraform validate
      
      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan
      
      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve


  terraform-destroy:
    if : github.event.inputs.action == 'Destroy'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_CLOUD_TOKEN }}
          terraform_version: 1.5.7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: |
          cd terraform
          terraform init
    
      - name: Terraform Validate
        run: |
          cd terraform
          terraform validate
      
      - name: Terraform Destroy
        run: |
          cd terraform
          terraform destroy -auto-approve

